name: Code Coverage Report
'on':
  workflow_dispatch: null
  push:
    paths-ignore:
      - '**.md'
      - .github/workflows/**.yml
    branches:
      - master
jobs:
  build:
    name: Code Coverage Report
    runs-on: eg-default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          overwrite-settings: false
      - name: Maven
        run: |
          mvn install package complie 
      - name: Code Coverage Reporter Action
        uses: Flex/code-coverage-reporter-action@v4
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          apiKey: '${{ secrets.CCR_ES_API_KEY }}'
          single_build: true
          module_name: api
          ccr_path: target/site/jacoco
          ccr_file: jacoco.xml
          coverage_reporter: jacoco
          workflow: base
      - name: Code Coverage Reporter Action
        uses: Flex/code-coverage-reporter-action@v4
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          apiKey: '${{ secrets.CCR_ES_API_KEY }}'
          single_build: true
          module_name: service
          ccr_path: target/site/jacoco
          ccr_file: jacoco.xml
          coverage_reporter: jacoco
          workflow: base
      - name: Code Coverage Reporter Action
        uses: Flex/code-coverage-reporter-action@v4
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          apiKey: '${{ secrets.CCR_ES_API_KEY }}'
          single_build: true
          module_name: web
          ccr_path: target/site/jacoco
          ccr_file: jacoco.xml
          coverage_reporter: jacoco
          workflow: base
